// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestBase.Shared.Data;

#nullable disable

namespace TestBase.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831193605_Fase6RapportForkastelse")]
    partial class Fase6RapportForkastelse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TestBase.Shared.Domain.Administrasjon.Administrator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("ArkivertUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("ErArkivert")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FulltNavn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("HprNr")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("MobilNr")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("OpprettetUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Personnummer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId")
                        .IsUnique();

                    b.ToTable("administratorer", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Administrasjon.Behandler", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Arbeidsadresse")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTimeOffset?>("ArkivertUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("BrukeravtaleGodkjentUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("BrukeravtaleGodkjentVersjon")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTimeOffset?>("EpostVerifisertUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Etternavn")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Fornavn")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("HprGodkjent")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("HprGodkjentAvAdministratorId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("HprGodkjentUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HprNr")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long?>("InvitertAvAdministratorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InvitertAvBehandlerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kontonummer")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MobilNr")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset?>("MobilVerifisertUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("OnskerDagligPaaminnelse")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("OpprettetUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaaminnelseKanal")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Personnummer")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset?>("RegistrertUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("SistPaaminnetUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Tittel")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("behandlere", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Administrasjon.BehandlerInvitasjon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BehandlerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("BruktUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KontaktMetode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("KontaktVerdi")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<long?>("OpprettetAvAdministratorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OpprettetAvBehandlerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("UtlopUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("behandler_invitasjoner", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Administrasjon.BehandlerKontaktVerifisering", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BehandlerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("BruktUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Forsok")
                        .HasColumnType("int");

                    b.Property<string>("Kanal")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("KodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("UtlopUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BehandlerId", "Kanal");

                    b.ToTable("behandler_kontakt_verifiseringer", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Administrasjon.BehandlerMelding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BehandlerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LestUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("OpprettetUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TestTildelingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestTildelingId");

                    b.HasIndex("BehandlerId", "LestUtc");

                    b.ToTable("behandler_meldinger", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Administrasjon.ToFaktorKode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("BruktUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Forsok")
                        .HasColumnType("int");

                    b.Property<string>("KodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("PrincipalId")
                        .HasColumnType("bigint");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("UtlopUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalType", "PrincipalId");

                    b.ToTable("to_faktor_koder", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Pasienter.Pasient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTimeOffset?>("ArkivertUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("BehandlerId")
                        .HasColumnType("bigint");

                    b.Property<string>("BiologiskKjonnVedFodsel")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset?>("BrukeravtaleGodkjentUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("BrukeravtaleGodkjentVersjon")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("GodtarLagringAvData")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("GodtarMuligVippsBetaling")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Gruppenavn")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Kjonnsidentitet")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("KjonnsidentitetSpesifisert")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("MobilNr")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Navn")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTimeOffset>("OpprettetUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Personnummer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset?>("RegistrertUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Varslingspreferanse")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("BehandlerId");

                    b.ToTable("pasienter", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Pasienter.PasientInvitasjon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("BruktUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KontaktMetode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("KontaktVerdi")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<long>("OpprettetAvBehandlerId")
                        .HasColumnType("bigint");

                    b.Property<long>("PasientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("UtlopUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("pasient_invitasjoner", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Tester.Test", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Belonningstekst")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Beskrivelse")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("ErAktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Kode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTimeOffset>("OpprettetUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.ToTable("tester", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Tester.TestKategori", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("OpprettetUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Navn")
                        .IsUnique();

                    b.ToTable("test_kategorier", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Tester.TestKategoriKobling", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.Property<long>("TestKategoriId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestKategoriId");

                    b.HasIndex("TestId", "TestKategoriId")
                        .IsUnique();

                    b.ToTable("test_kategori_koblinger", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Tester.TestLedd", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Instruksjon")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("int");

                    b.Property<string>("Sporsmalstekst")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Svaralternativer")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Svartype")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("TestSideId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestSideId");

                    b.ToTable("test_ledd", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Tester.TestSide", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Instruksjon")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("int");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("test_sider", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Tester.TestSvar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("BesvartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SvarVerdi")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<long>("TestLeddId")
                        .HasColumnType("bigint");

                    b.Property<long>("TestTildelingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestTildelingId", "TestLeddId")
                        .IsUnique();

                    b.ToTable("test_svar", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Domain.Tester.TestTildeling", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("Frist")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("FullfortUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PasientId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RapportForkastetUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("RapportGodkjentUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("RapportSynligForPasient")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("StartetUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TildeltAvAdministratorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TildeltAvBehandlerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TildeltUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("VarighetMinutter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PasientId");

                    b.HasIndex("TestId");

                    b.ToTable("test_tildelinger", (string)null);
                });

            modelBuilder.Entity("TestBase.Shared.Security.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_log_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
